:package: Conflict with symfony/password-hasher version <6.4
```
Error: Call to undefined method Symfony\Component\Security\Core\User\InMemoryUser::getSalt()

/home/runner/work/graphqlite-bundle/graphqlite-bundle/vendor/symfony/password-hasher/Hasher/UserPasswordHasher.php:80
```